apiVersion: apps/v1
kind: Deployment
metadata:
  name: etc-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etc-writer
  template:
    metadata:
      labels:
        app: etc-writer
    spec:
      containers:
      - name: etc-writer
        image: localhost/etc-writer
        resources:
          limits:
            memory: "256Mi"
            cpu: "750m"