apiVersion: apps/v1
kind: Deployment
metadata:
  name: shellrunncr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shellrunner
  template:
    metadata:
      labels:
        app: shellrunner
    spec:
      containers:
      - name: shellrunner
        image: sysdigtraining/shell_runncr
        resources:
          limits:
            memory: "256Mi"
            cpu: "750m"