apiVersion: apps/v1
kind: Deployment
metadata:
  name: my_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my_app
  template:
    metadata:
      labels:
        app: my_app
    spec:
      containers:
      - name: my_app-container
        image: localhost/my_app
        resources:
          limits:
            memory: "256Mi"
            cpu: "750m"
        ports:
        - containerPort: 8081